version: '3'
services:
  ff:
    image: darron/ff:b6356ffc8010bca7ffc30558539b414b76cc09be
    ports:
      - 8080:8080
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_BEARER_TOKEN=${JWT_BEARER_TOKEN}
      - REDIS=redis:6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
