version: '3'
services:
  ff:
    image: darron/ff:b2720c6e8d88bd0487e99fca891a7806e6ab1633
    ports:
      - 8080:8080
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_BEARER_TOKEN=${JWT_BEARER_TOKEN}
      - REDIS=redis:6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
